# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coture
email: zlxricky@gmail.com
description: 遇风尘之会，必有凌霄之志
baseurl: "/blog" # the subpath of your site, e.g. /blog

# Build settings
markdown: redcarpet
excerpt_separator: "<!-- more -->"
redcarpet:
    extensions: [ "tables" ]

# pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"
